# =============================================================================
# Unified Model & Output Configuration
# =============================================================================

model:
  architecture: bilstm        # lstm | bilstm | gru | custom
  units: 1 #100
  layers: 1 #2
  dropout: 0.2
  activation: tanh
  optimizer: adam
  loss: mse

training:
  epochs: 1
  batch_size: 1024
  patience: 10

evaluation:
  eval_batch_size: 1024

data:
  seq_length: 60
  train_ratio: 0.8
  val_ratio: 0.1

output:
  checkpoints:
    model_dir: models/checkpoints
    scaler_dir: models/scalers

  metrics:
    metrics_dir: analytics/metrics

  predictions:
    pred_dir: analytics/predictions

versioning:
  datetime_format: '%Y-%m-%d-%H-%M-%S'